---
deployment:
  tasks:
    # Set deployment path to the public_html directory (adjust this path as needed for your cPanel account)
    - export DEPLOYPATH=/home/boltgun/public_html/
    
    # Deploy the pre-built application (built locally)
    - /bin/cp -R .next/. $DEPLOYPATH/.next/
    - /bin/cp -R public/. $DEPLOYPATH/public/
    - /bin/cp server.js $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp next.config.js $DEPLOYPATH/
    
    # Set proper permissions
    - /bin/chmod 755 $DEPLOYPATH
