# Bolt Gun Nation - Cloudflare Pages Configuration
name = "bolt-gun-nation"
compatibility_date = "2025-07-23"

# Pages Configuration
# This tells Cloudflare where to find the built Next.js output
pages_build_output_dir = "out"

# Environment Variables
# Add any environment variables your application needs here
# Example:
# [env.production]
# MY_VAR = "production-value"

# Important: Build command must be configured in Cloudflare Pages dashboard
# Recommended build command: npm install && npm run build
# Do NOT use npm ci as it requires perfect package.json/package-lock.json sync
